workflows:
  android-release:
    name: Files AAB Build

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew bundleRelease -x signReleaseBundle

    artifacts:
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - princear@example.com
