workflows:
  android-release:
    name: Android Release AAB

    instance_type: mac_mini_m2

    environment:
      java: 17

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew bundleRelease -x signReleaseBundle

    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
