workflows:
  android-release:
    name: Android Release AAB (NexVora Ready)
    max_build_duration: 120

    environment:
      java: 17

      android_signing:
        - keystore_reference

      vars:
        PACKAGE_NAME: "com.aistudio.files.go.kxmpzq"
        GRADLEW_PATH: "./gradlew"

    scripts:

      - name: Checkout
        script: |
          git checkout .

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Clean project
        script: |
          chmod +x ./gradlew
          ./gradlew clean

      - name: Build Release AAB
        script: |
          ./gradlew bundleRelease \
          --stacktrace \
          --no-daemon

    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - dev@nexvora.com
